/**
 * Handyman task templates — tool names must match src/toolCatalog.js RECOMMENDED_TOOLS.
 */
export const HANDYMAN_TASK_TEMPLATES = [
  {
    name: "Hang shelves",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Stud Finder",
      "Drill/Driver",
      "Impact Driver",
      "Impact-Rated Bit Set",
      "Screwdriver Set",
      "Pry Bar",
      "Safety Glasses",
    ],
  },
  {
    name: "Mount TV on wall",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Stud Finder",
      "Drill/Driver",
      "Impact Driver",
      "Hammer Drill",
      "Impact-Rated Bit Set",
      "Socket & Ratchet Set",
      "Safety Glasses",
    ],
  },
  {
    name: "Install door hardware",
    tools: [
      "Tape Measure",
      "Drill/Driver",
      "Impact Driver",
      "Hole Saw Kit",
      "Screwdriver Set",
      "Chalk Line",
      "Utility Knife",
      "Safety Glasses",
    ],
  },
  {
    name: "Repair drywall hole",
    tools: [
      "Tape Measure",
      "Utility Knife",
      "Putty Knife Set",
      "Sanding Block",
      "Random Orbital Sander",
      "Shop Vac",
      "Drop Cloths",
      "Safety Glasses",
      "Respirator",
    ],
  },
  {
    name: "Patch and paint wall",
    tools: [
      "Putty Knife Set",
      "Sanding Block",
      "Painter's Tape",
      "Drop Cloths",
      "Paint Brushes",
      "Paint Rollers",
      "Utility Knife",
      "Shop Vac",
      "Safety Glasses",
    ],
  },
  {
    name: "Paint interior room",
    tools: [
      "Tape Measure",
      "Painter's Tape",
      "Drop Cloths",
      "Paint Brushes",
      "Paint Rollers",
      "Caulk Gun",
      "Putty Knife Set",
      "Step Ladder",
      "Extension Ladder",
      "Shop Vac",
      "Safety Glasses",
    ],
  },
  {
    name: "Install ceiling fan",
    tools: [
      "Step Ladder",
      "Tape Measure",
      "4ft Level",
      "Stud Finder",
      "Drill/Driver",
      "Impact Driver",
      "Non-Contact Voltage Tester",
      "Multimeter",
      "Wire Stripper",
      "Lineman Pliers",
      "Needle Nose Pliers",
      "Electrical Tape",
      "Safety Glasses",
    ],
  },
  {
    name: "Replace light fixture",
    tools: [
      "Step Ladder",
      "Non-Contact Voltage Tester",
      "Multimeter",
      "Wire Stripper",
      "Lineman Pliers",
      "Needle Nose Pliers",
      "Screwdriver Set",
      "Drill/Driver",
      "Electrical Tape",
      "Safety Glasses",
    ],
  },
  {
    name: "Replace outlet or switch",
    tools: [
      "Non-Contact Voltage Tester",
      "Outlet/GFCI Tester",
      "Wire Stripper",
      "Lineman Pliers",
      "Needle Nose Pliers",
      "Screwdriver Set",
      "Precision Screwdriver Set",
      "Electrical Tape",
      "Safety Glasses",
    ],
  },
  {
    name: "Install GFCI outlet",
    tools: [
      "Non-Contact Voltage Tester",
      "Outlet/GFCI Tester",
      "Wire Stripper",
      "Lineman Pliers",
      "Needle Nose Pliers",
      "Screwdriver Set",
      "Electrical Tape",
      "Safety Glasses",
    ],
  },
  {
    name: "Install smoke or CO detector",
    tools: [
      "Step Ladder",
      "Drill/Driver",
      "Impact Driver",
      "Stud Finder",
      "Tape Measure",
      "Safety Glasses",
    ],
  },
  {
    name: "Install smart thermostat",
    tools: [
      "Non-Contact Voltage Tester",
      "Multimeter",
      "Wire Stripper",
      "Lineman Pliers",
      "Needle Nose Pliers",
      "Screwdriver Set",
      "Precision Screwdriver Set",
      "4ft Level",
      "Safety Glasses",
    ],
  },
  {
    name: "Replace faucet",
    tools: [
      "Basin Wrench",
      "Adjustable Wrench Set",
      "Channel Lock Pliers",
      "Tubing Cutter",
      "Putty Knife Set",
      "Plumber's Putty",
      "Thread Seal Tape",
      "Shop Vac",
      "Drop Cloths",
      "Safety Glasses",
    ],
  },
  {
    name: "Repair leaky faucet",
    tools: [
      "Adjustable Wrench Set",
      "Channel Lock Pliers",
      "Basin Wrench",
      "Screwdriver Set",
      "Plumber's Putty",
      "Thread Seal Tape",
      "Drop Cloths",
    ],
  },
  {
    name: "Unclog sink or tub drain",
    tools: [
      "Drain Auger",
      "Channel Lock Pliers",
      "Adjustable Wrench Set",
      "Basin Wrench",
      "Shop Vac",
      "Work Gloves",
      "Safety Glasses",
    ],
  },
  {
    name: "Replace toilet fill valve or flapper",
    tools: [
      "Adjustable Wrench Set",
      "Channel Lock Pliers",
      "Screwdriver Set",
      "Shop Vac",
      "Drop Cloths",
      "Work Gloves",
    ],
  },
  {
    name: "Caulk tub or shower",
    tools: [
      "Utility Knife",
      "Caulk Gun",
      "Putty Knife Set",
      "Painter's Tape",
      "Drop Cloths",
      "Shop Vac",
      "Work Gloves",
    ],
  },
  {
    name: "Install dishwasher connection",
    tools: [
      "Adjustable Wrench Set",
      "Channel Lock Pliers",
      "Tubing Cutter",
      "Thread Seal Tape",
      "Screwdriver Set",
      "Shop Vac",
      "Drop Cloths",
    ],
  },
  {
    name: "Install blinds or curtain rod",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Drill/Driver",
      "Impact Driver",
      "Impact-Rated Bit Set",
      "Stud Finder",
      "Step Ladder",
      "Safety Glasses",
    ],
  },
  {
    name: "Mount mirrors or pictures",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Stud Finder",
      "Drill/Driver",
      "Impact Driver",
      "Impact-Rated Bit Set",
      "Hammer Drill",
      "Safety Glasses",
    ],
  },
  {
    name: "Assemble furniture",
    tools: [
      "Drill/Driver",
      "Impact Driver",
      "Impact-Rated Bit Set",
      "Screwdriver Set",
      "Precision Screwdriver Set",
      "Rubber Mallet",
      "Tape Measure",
      "4ft Level",
      "Knee Pads",
    ],
  },
  {
    name: "Adjust cabinet doors and hinges",
    tools: [
      "Screwdriver Set",
      "Precision Screwdriver Set",
      "Drill/Driver",
      "4ft Level",
      "Tape Measure",
      "Rubber Mallet",
    ],
  },
  {
    name: "Install baseboard or trim",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Speed Square",
      "Circular Saw",
      "Jigsaw",
      "Oscillating Multi-Tool",
      "Brad Nailer",
      "Drill/Driver",
      "Impact Driver",
      "Bar Clamps",
      "Quick-Grip Clamps",
      "Sanding Block",
      "Safety Glasses",
      "Hearing Protection",
    ],
  },
  {
    name: "Replace interior door",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Speed Square",
      "Circular Saw",
      "Jigsaw",
      "Drill/Driver",
      "Impact Driver",
      "Screwdriver Set",
      "Pry Bar",
      "Bar Clamps",
      "Safety Glasses",
    ],
  },
  {
    name: "Weatherstrip door or window",
    tools: [
      "Tape Measure",
      "Utility Knife",
      "Putty Knife Set",
      "Screwdriver Set",
      "Drill/Driver",
      "Pry Bar",
      "Safety Glasses",
    ],
  },
  {
    name: "Repair fence gate",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Speed Square",
      "Circular Saw",
      "Reciprocating Saw",
      "Drill/Driver",
      "Impact Driver",
      "Socket & Ratchet Set",
      "Bar Clamps",
      "Claw Hammer",
      "Safety Glasses",
      "Work Gloves",
    ],
  },
  {
    name: "Replace deck boards",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Speed Square",
      "Circular Saw",
      "Reciprocating Saw",
      "Oscillating Multi-Tool",
      "Drill/Driver",
      "Impact Driver",
      "Pry Bar",
      "Sanding Block",
      "Safety Glasses",
      "Hearing Protection",
      "Work Gloves",
    ],
  },
  {
    name: "Clean and seal grout",
    tools: [
      "Utility Knife",
      "Oscillating Multi-Tool",
      "Putty Knife Set",
      "Shop Vac",
      "Drop Cloths",
      "Work Gloves",
      "Respirator",
      "Knee Pads",
    ],
  },
  {
    name: "Install towel bar or toilet paper holder",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Stud Finder",
      "Drill/Driver",
      "Impact Driver",
      "Hammer Drill",
      "Impact-Rated Bit Set",
      "Safety Glasses",
    ],
  },
  {
    name: "Replace garbage disposal",
    tools: [
      "Adjustable Wrench Set",
      "Channel Lock Pliers",
      "Basin Wrench",
      "Screwdriver Set",
      "Shop Vac",
      "Drop Cloths",
      "Work Gloves",
      "Safety Glasses",
    ],
  },
  {
    name: "Install child safety hardware",
    tools: [
      "Tape Measure",
      "Stud Finder",
      "Drill/Driver",
      "Impact Driver",
      "Impact-Rated Bit Set",
      "Screwdriver Set",
      "Safety Glasses",
    ],
  },
  {
    name: "Exterior caulking and sealing",
    tools: [
      "Step Ladder",
      "Extension Ladder",
      "Caulk Gun",
      "Utility Knife",
      "Putty Knife Set",
      "Painter's Tape",
      "Drop Cloths",
      "Safety Glasses",
      "Work Gloves",
    ],
  },
  {
    name: "Gutter cleaning and minor repair",
    tools: [
      "Extension Ladder",
      "Ladder Levelers",
      "Shop Vac",
      "Reciprocating Saw",
      "Drill/Driver",
      "Impact Driver",
      "Safety Glasses",
      "Work Gloves",
      "Headlamp",
    ],
  },
  {
    name: "Install grab bars",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Stud Finder",
      "Drill/Driver",
      "Impact Driver",
      "Hammer Drill",
      "Impact-Rated Bit Set",
      "Safety Glasses",
    ],
  },
  {
    name: "Replace dryer vent cover",
    tools: [
      "Drill/Driver",
      "Impact Driver",
      "Reciprocating Saw",
      "Oscillating Multi-Tool",
      "Caulk Gun",
      "Tape Measure",
      "Step Ladder",
      "Safety Glasses",
    ],
  },
  {
    name: "Hang interior pre-hung door",
    tools: [
      "Tape Measure",
      "4ft Level",
      "Shims", // not in catalog - remove
    ],
  },
];
