export const TOOL_CATEGORIES = [
  "Measuring & Layout",
  "Cutting & Drilling",
  "Fastening & Assembly",
  "Electrical",
  "Plumbing",
  "Finishing & Prep",
  "Ladders & Access",
  "Cleanup & Protection",
];

export const RECOMMENDED_TOOLS = [
  { name: "Tape Measure", category: "Measuring & Layout" },
  { name: "Laser Distance Measurer", category: "Measuring & Layout" },
  { name: "4ft Level", category: "Measuring & Layout" },
  { name: "Torpedo Level", category: "Measuring & Layout" },
  { name: "Speed Square", category: "Measuring & Layout" },
  { name: "Chalk Line", category: "Measuring & Layout" },
  { name: "Stud Finder", category: "Measuring & Layout" },
  { name: "Combination Square", category: "Measuring & Layout" },
  { name: "Moisture Meter", category: "Measuring & Layout" },
  { name: "Infrared Thermometer", category: "Measuring & Layout" },
  { name: "Laser Level", category: "Measuring & Layout" },
  { name: "Drill/Driver", category: "Cutting & Drilling" },
  { name: "Impact Driver", category: "Cutting & Drilling" },
  { name: "Hammer Drill", category: "Cutting & Drilling" },
  { name: "Circular Saw", category: "Cutting & Drilling" },
  { name: "Jigsaw", category: "Cutting & Drilling" },
  { name: "Reciprocating Saw", category: "Cutting & Drilling" },
  { name: "Oscillating Multi-Tool", category: "Cutting & Drilling" },
  { name: "Angle Grinder", category: "Cutting & Drilling" },
  { name: "Hole Saw Kit", category: "Cutting & Drilling" },
  { name: "Impact-Rated Bit Set", category: "Cutting & Drilling" },
  { name: "Right-Angle Drill Attachment", category: "Cutting & Drilling" },
  { name: "Screwdriver Set", category: "Fastening & Assembly" },
  { name: "Precision Screwdriver Set", category: "Fastening & Assembly" },
  { name: "Nut Driver Set", category: "Fastening & Assembly" },
  { name: "Socket & Ratchet Set", category: "Fastening & Assembly" },
  { name: "Adjustable Wrench Set", category: "Fastening & Assembly" },
  { name: "Claw Hammer", category: "Fastening & Assembly" },
  { name: "Rubber Mallet", category: "Fastening & Assembly" },
  { name: "Pry Bar", category: "Fastening & Assembly" },
  { name: "Bar Clamps", category: "Fastening & Assembly" },
  { name: "Quick-Grip Clamps", category: "Fastening & Assembly" },
  { name: "Rivet Tool", category: "Fastening & Assembly" },
  { name: "Brad Nailer", category: "Fastening & Assembly" },
  { name: "Staple Gun", category: "Fastening & Assembly" },
  { name: "Multimeter", category: "Electrical" },
  { name: "Non-Contact Voltage Tester", category: "Electrical" },
  { name: "Outlet/GFCI Tester", category: "Electrical" },
  { name: "Wire Stripper", category: "Electrical" },
  { name: "Crimping Tool", category: "Electrical" },
  { name: "Fish Tape", category: "Electrical" },
  { name: "Lineman Pliers", category: "Electrical" },
  { name: "Needle Nose Pliers", category: "Electrical" },
  { name: "Diagonal Cutters", category: "Electrical" },
  { name: "Electrical Tape", category: "Electrical" },
  { name: "Channel Lock Pliers", category: "Plumbing" },
  { name: "Pipe Wrench", category: "Plumbing" },
  { name: "Basin Wrench", category: "Plumbing" },
  { name: "Tubing Cutter", category: "Plumbing" },
  { name: "Plumber's Wrench Set", category: "Plumbing" },
  { name: "Adjustable Basin/Faucet Tool", category: "Plumbing" },
  { name: "Drain Auger", category: "Plumbing" },
  { name: "Plumber's Putty", category: "Plumbing" },
  { name: "Thread Seal Tape", category: "Plumbing" },
  { name: "Caulk Gun", category: "Finishing & Prep" },
  { name: "Putty Knife Set", category: "Finishing & Prep" },
  { name: "Sanding Block", category: "Finishing & Prep" },
  { name: "Random Orbital Sander", category: "Finishing & Prep" },
  { name: "Paint Brushes", category: "Finishing & Prep" },
  { name: "Paint Rollers", category: "Finishing & Prep" },
  { name: "Painter's Tape", category: "Finishing & Prep" },
  { name: "Utility Knife", category: "Finishing & Prep" },
  { name: "Extension Ladder", category: "Ladders & Access" },
  { name: "Step Ladder", category: "Ladders & Access" },
  { name: "Ladder Levelers", category: "Ladders & Access" },
  { name: "Scaffolding Plank", category: "Ladders & Access" },
  { name: "Shop Vac", category: "Cleanup & Protection" },
  { name: "Drop Cloths", category: "Cleanup & Protection" },
  { name: "Knee Pads", category: "Cleanup & Protection" },
  { name: "Safety Glasses", category: "Cleanup & Protection" },
  { name: "Hearing Protection", category: "Cleanup & Protection" },
  { name: "Respirator", category: "Cleanup & Protection" },
  { name: "Work Gloves", category: "Cleanup & Protection" },
  { name: "Headlamp", category: "Cleanup & Protection" },
  { name: "Portable Work Light", category: "Cleanup & Protection" },
];
